GET https://pos.pages.fm/api/v1/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRMawxqFuZyBUdeG6pW4gS2nhu4d0IiwiZXhwIjoxNzU1NDIzNTI5LCJhcHBsaWNhdGlvbiI6MSwidWlkIjoiYmQ5MDE5MDQtMzhmZC00ZTRkLWE4MzktMWFkYzFlNjUxZjU0Iiwic2Vzc2lvbl9pZCI6IlhxckRNb2tqb2xGSVhqc3JNYnpnSkZhTGw5OVhmNjMwSlJZd2JWY3JBRm8iLCJpYXQiOjE3NDc2NDc1MjksImZiX2lkIjoiMTgxODU4Njk2NTA0MDU4NiIsImxvZ2luX3Nlc3Npb24iOm51bGwsImZiX25hbWUiOiJExrDGoW5nIFR14bqlbiBLaeG7h3QifQ.5P3ePkVcDXievugPd7Vs4wq3GnLSUvjkRSsEajTYTas

###

POST https://pos.pancake.vn/api/v1/auth/login
Content-Type: application/json

{
  "email": "your@email.com",
  "password": "your_password"
}

###

Get https://pages.fm/api/v1/pages?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRMawxqFuZyBUdeG6pW4gS2nhu4d0IiwiZXhwIjoxNzU1NDIzNTI5LCJhcHBsaWNhdGlvbiI6MSwidWlkIjoiYmQ5MDE5MDQtMzhmZC00ZTRkLWE4MzktMWFkYzFlNjUxZjU0Iiwic2Vzc2lvbl9pZCI6IlhxckRNb2tqb2xGSVhqc3JNYnpnSkZhTGw5OVhmNjMwSlJZd2JWY3JBRm8iLCJpYXQiOjE3NDc2NDc1MjksImZiX2lkIjoiMTgxODU4Njk2NTA0MDU4NiIsImxvZ2luX3Nlc3Npb24iOm51bGwsImZiX25hbWUiOiJExrDGoW5nIFR14bqlbiBLaeG7h3QifQ.5P3ePkVcDXievugPd7Vs4wq3GnLSUvjkRSsEajTYTas
Content-Type: application/json,
Accept: application/json

###

GET https://pages.fm/api/public_api/v2/pages?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRMawxqFuZyBUdeG6pW4gS2nhu4d0IiwiZXhwIjoxNzU1NDIzNTI5LCJhcHBsaWNhdGlvbiI6MSwidWlkIjoiYmQ5MDE5MDQtMzhmZC00ZTRkLWE4MzktMWFkYzFlNjUxZjU0Iiwic2Vzc2lvbl9pZCI6IlhxckRNb2tqb2xGSVhqc3JNYnpnSkZhTGw5OVhmNjMwSlJZd2JWY3JBRm8iLCJpYXQiOjE3NDc2NDc1MjksImZiX2lkIjoiMTgxODU4Njk2NTA0MDU4NiIsImxvZ2luX3Nlc3Npb24iOm51bGwsImZiX25hbWUiOiJExrDGoW5nIFR14bqlbiBLaeG7h3QifQ.5P3ePkVcDXievugPd7Vs4wq3GnLSUvjkRSsEajTYTas/
