# syntax=docker/dockerfile:1.0.0-experimental
# Odoo 14 base
# version 4.0

FROM python:3.7-slim-buster

ENV LANG C.UTF-8

COPY packages /etc/packages
COPY odoo14-requirements.txt /etc/

RUN set -x; \
        apt-get update && \
        DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
# necessary base packages for odoo
            ca-certificates \
            curl \
            git wget \
            gnupg2 \
            python3-dev \
            python3-pip \
            python3-renderpm \
            python3-setuptools \
            python3-wheel \
            python3-watchdog \
            libssl-dev \
            libjpeg62-turbo \
            multiarch-support \
            xz-utils \
            gcc \
            bzr zip unzip \       
            pysassc \
            libfontconfig1 libxrender1 libxext6 \
            fontconfig xfonts-75dpi xfonts-base \
            build-essential libldap2-dev libsasl2-dev ldap-utils \
            locales; \
# necessary packages for wkhtmltopdf
            dpkg -i /etc/packages/*.deb && \
            rm -r /etc/packages/; \
# install nodejs
            curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
            apt-get install nodejs -y && npm install -g postcss rtlcss less less-plugin-clean-css; \
# setting locale
            sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen; \
# install postgresql 10
            echo 'deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main' >  /etc/apt/sources.list.d/pgdg.list && \
            wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
            apt-get update && \
            apt-get install -y postgresql-client-10; \
# install python3 libs 
            pip3 install --no-cache-dir --upgrade pip && \
            pip3 install --no-cache-dir --upgrade redis && \
            pip3 install --no-cache-dir -r /etc/odoo14-requirements.txt; \
# clean apt cache
            apt-get autoremove -y && \
            apt-get clean

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
