# renew_before_expiry = 30 days
version = 2.1.0
archive_dir = /etc/letsencrypt/archive/crm.tuankiet.media
cert = /etc/letsencrypt/live/crm.tuankiet.media/cert.pem
privkey = /etc/letsencrypt/live/crm.tuankiet.media/privkey.pem
chain = /etc/letsencrypt/live/crm.tuankiet.media/chain.pem
fullchain = /etc/letsencrypt/live/crm.tuankiet.media/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 7af98a458e8afc28103d7617baa9aa0b
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
