# renew_before_expiry = 30 days
version = 2.1.0
archive_dir = /etc/letsencrypt/archive/n8n.tuankiet.media
cert = /etc/letsencrypt/live/n8n.tuankiet.media/cert.pem
privkey = /etc/letsencrypt/live/n8n.tuankiet.media/privkey.pem
chain = /etc/letsencrypt/live/n8n.tuankiet.media/chain.pem
fullchain = /etc/letsencrypt/live/n8n.tuankiet.media/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 71c1236cdd7b7605e502b28253c38cd9
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
